import { UsuarioAdminSearchFilter, UsuarioSearchFilter } from 'src/app/models/shared/service-types.model';
import { JwtUserModel } from 'src/app/models/security/jwtUser.model';
import { UserModel } from 'src/app/models/security/user.model';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { PaginatedData } from 'src/app/models/api/api-response.model';
import { ActividadViewModel } from 'src/app/models/logs/logs-vm.model';
import { DropdownViewModel } from 'src/app/models/parametros/parametros-vm.model';
import { PerfilUsuarioViewModel, UsuarioAvatarViewModel, UsuarioViewModel } from 'src/app/models/seguridad/seguridad-vm.model';

@Injectable()
export abstract class IHttpSecurityService {
  abstract getCurrentUser(): JwtUserModel;
  abstract getCurrentUserAsObservable(): Observable<JwtUserModel>;
  abstract getUsuarios(search: UsuarioSearchFilter): Observable<PaginatedData<UsuarioViewModel>>;
  abstract getUsuariosAdmin(search: UsuarioAdminSearchFilter): Observable<PaginatedData<UsuarioViewModel>>;
  abstract getLoggedUserByJwt(): Observable<PerfilUsuarioViewModel>;
  abstract getUserByUserName(userName: string): Observable<PerfilUsuarioViewModel>;
  abstract getSesiones(): Observable<PaginatedData<unknown>>;
  abstract deleteSessionById(sessionId: number): Observable<boolean>;
  abstract setUserToLocalStorage(obj: any): any;
  abstract registerUser(user: UserModel): Observable<number>;
  abstract loginUser(user: { userName: string; password: string }): Observable<JwtUserModel>;
  abstract refreshAccessToken(): Observable<string>;
  abstract logout(): any;
  abstract changePassword(obj: { currentPassword: string; newPassword: string }): Observable<boolean>;
  abstract updateUsuario(usuario: UsuarioViewModel): Observable<boolean>;
  abstract getUsuarioInfo(userName: string): Observable<PerfilUsuarioViewModel>;
  abstract seguirUsuario(usuario: { userName: string }): Observable<boolean>;
  abstract isFollowingTheUser(userName: string): Observable<boolean>;
  abstract getFollowingUsersByUserId(id: number): Observable<PaginatedData<UsuarioAvatarViewModel>>;
  abstract getFollowersByUserId(userId: number): Observable<PaginatedData<UsuarioAvatarViewModel>>;
  abstract getLastFollowersByUserId(userId: number): Observable<UsuarioAvatarViewModel[]>;
  abstract savePerfilInfo(perfil: Partial<PerfilUsuarioViewModel>): Observable<boolean>;
  abstract getCurrentPerfilInfo(): Observable<PerfilUsuarioViewModel>;
  abstract getPerfilInfoByUserId(userId: number): Observable<PerfilUsuarioViewModel>;
  abstract getSocialMediaByUsuarioId(usuarioId: number): Observable<unknown>;
  abstract banUser(usuario: { userName: string; razon?: string }): Observable<boolean>;
  abstract changeAvatar(file: Blob): Observable<string>;
  abstract changeAvatarAdmin(file: Blob, usuarioId: number): Observable<string>;
  abstract getLastRegisteredUsers(): Observable<UsuarioViewModel[]>;
  abstract getRangosUsuarios(): Observable<PaginatedData<unknown>>;
  abstract getRangosDropdown(): Observable<DropdownViewModel[]>;
  abstract getActividadUsuario(usuarioId: number, tipoActividad: number): Observable<ActividadViewModel[]>;
  abstract addUpdateRango(rango: unknown): Observable<number>;
  abstract changeRango(rangoUsuario: { userId: number; rangoId: number }): Observable<boolean>;
  abstract sessionOnlineUser(): Observable<boolean>;
  abstract changeBackgroundProfile(obj: { imageUrl: string }): Observable<boolean>;
  abstract getAdminsList(): Observable<UsuarioViewModel[]>;
  abstract changeUsuariosRangosByPuntos(): Observable<boolean>;
  abstract getUserStatus(userName: string): Observable<unknown>;
  abstract removeAvatar(usuarioId: number): Observable<boolean>;
  abstract removeUsuario(usuarioId: number): Observable<boolean>;
}
